{% set name = "robotframework-browser" %}
{% set version = "17.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robotframework-browser-{{ version }}.tar.gz
  sha256: ec68e5779fe8d76408e341ce603912746d0c3eeb5253bfcf155a7a29333ac082

build:
  entry_points:
    - rfbrowser=Browser.entry:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - nodejs >=18.0

  run:
    - python >=3.8,<4.0
    - nodejs >=18.0
    - grpcio
    - grpcio-tools
    - protobuf
    - robotframework >=5.0.1
    - robotframework-pythonlibcore >=4.2.0
    - robotframework-assertion-engine >=2.0.0,<3.0.0
    - typing-extensions >=4.5.0
    - wrapt >=1.15.0
    - overrides >=7.3.1
    - click >=8.1.7

test:
  imports:
    - Browser
  commands:
    - rfbrowser --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-browser
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Robot Framework Browser library powered by Playwright.
  description: |
    Robot Framework Browser library powered by Playwright. Moving browser automation to year 2020 (or 2021)!
    Aiming for speed, reliability and visibility.
  doc_url: https://marketsquare.github.io/robotframework-browser/Browser.html
  dev_url: https://github.com/MarketSquare/robotframework-browser

extra:
  recipe-maintainers:
    - martinRenou
    - xylix
    - conda-forge/rpaframework-core
